name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r requirements/test.txt -r requirements.txt

      - name: Docs
        run: |
          make docs
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "There were modifications after running make docs"
            git diff
            exit 1
          fi

      - name: Lint
        run: make lint

      - name: mypy
        run: make mypy

      - name: pytest
        run: make pytest

      - name: validatortest
        run: make validatortest
